### ISSUE TITLE
Why does circleCI have counts?

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-action-counter-db#1]
When I look at the repos that are listed for circleCI many of them haven't had builds in ages. Is this because they haven't been rerendered recently and still retain the circle scripts?

**Comment by CJ-Wright** [comment]
@beckermr

**Comment by beckermr** [comment]
I record everything that ever happened in the lists of repos. Only the data per time bucket is refreshed.

**Comment by CJ-Wright** [comment]
Ahh ok, thank you!
